### PR TITLE
Feature/str slice null check

### PR DESCRIPTION
**Pull request by koliyo**
Add StrSlice.to_std_string null check

### CODE REVIEW

**Comment by jzimmerman** [comment]
I don't think the function should fail silently if the pointer is null. Can you say a bit more about why you are suggesting this change -- when do you expect to encounter null rc_ptrs in StrSlices?

**Comment by koliyo** [comment]
Well I tried creating an AST token node by hand by simply calling the constructor. Maybe the value is maybe never null when passing through the parser, but I disagree that segfaulting is better than returning an empty string.

I guess it is a matter of philosophical approach when it comes to error handling, and I think avoiding hard crashes should always be avoided if possible. I think the approach described by John Ousterhout regarding error handling is a good starting point. https://youtu.be/bmSAYlu0NcY?t=1312

**Comment by jzimmerman** [comment]
> Well I tried creating an AST token node by hand by simply calling the constructor.

Yes, this should not be done -- that's not a valid StrSlice. I've added a comment to the constructor to that effect. (Ordinarily, I would delete the constructor, but it's used in some internal automatically-generated code.)

> I guess it is a matter of philosophical approach when it comes to error handling, and I think avoiding hard crashes should always be avoided if possible.

This is a subtle distinction. Ousterhout's idea, if I understand correctly, is to generalize the semantics of the operation to avoid error conditions. I agree with doing this _when it makes sense_ -- but this is not the same thing as failing silently. Hiding actual semantic errors by failing silently is often much worse.

**Comment by koliyo** [comment]
Ok, yeah I can see why the empty constructor should normally not be used. And preferably it should then be deleted/private as you say. If you need empty construction internally I would suggest some kind of more explicit static factory method, like `auto t = MyToken::alloc()` or similar, which would allow the constructor to be private only.

I think it is reasonable to not have silent errors as you want in this case, but just hard crashing with segfault is never a good option imo. In that case I think it is better to use exceptions to signal API user errors.

But ok, if you don't think this PR is a helpful contribution you are welcome to close it. I am not expecting to use the empty constructors in my code, it was just something I tested when fooling around a bit with the generated AST nodes.

I think this is a really interesting project overall!

**Comment by jzimmerman** [comment]
Yeah, ordinarily I would simply delete the default constructor, but it's used by a bunch of auto-generated code.

Thanks for your interest in the project -- hope you find it useful!

**Pull request closed without merging**
